language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # print the version for logging
  - docker --version
  # Build
  - docker-compose -f docker-compose-build.yaml build
  # Tagging
  - docker tag udagram-api-feed tienhuynhlt/udagram-api-feed:latest
  - docker tag udagram-api-user tienhuynhlt/udagram-api-user:latest
  - docker tag udagram-frontend tienhuynhlt/udagram-frontend:latest
  - docker tag reverseproxy tienhuynhlt/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push
  - docker push tienhuynhlt/udagram-api-feed:latest
  - docker push tienhuynhlt/udagram-api-user:latest
  - docker push tienhuynhlt/udagram-frontend:latest
  - docker push tienhuynhlt/reverseproxy:latest